테스트 제거

diff --git a/.github/workflows/testci.yml b/.github/workflows/testci.yml
--- a/.github/workflows/testci.yml
+++ b/.github/workflows/testci.yml
@@ -48,8 +48,8 @@ jobs:
     - name: Build With Gradle
       run: ./gradlew build -x test
 
-    - name: 테스트 코드 실행
-      run: ./gradlew --info test
+    #- name: 테스트 코드 실행
+     # run: ./gradlew --info test
 
      #- name: Publish Unit Test Results
      # uses: EnricoMi/publish-unit-test-result-action@v1
@@ -57,8 +57,8 @@ jobs:
      # with:
      #   files: build/test-results/**/*.xml
         
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure()
-      with:
-        report_paths: '**/build/test-results/test/TEST-*.xml'
+    #- name: Publish Test Report
+     # uses: mikepenz/action-junit-report@v3
+      #if: success() || failure()
+     # with:
+      #  report_paths: '**/build/test-results/test/TEST-*.xml'
